@ASP_NET_12._TaskFlow_Authentication_and_Authorizaton_HostAddress = http://localhost:5027

GET {{ASP_NET_12._TaskFlow_Authentication_and_Authorizaton_HostAddress}}/weatherforecast/
Accept: application/json

###
