@ASP_NET_16._TaskFlow_Resource_Based_Authorization_HostAddress = http://localhost:5183

GET {{ASP_NET_16._TaskFlow_Resource_Based_Authorization_HostAddress}}/weatherforecast/
Accept: application/json

###
